GCCFLAGS=-g -Os -Wall -mmcu=atmega328 
LINKFLAGS=-Wl,-u,vfprintf -lprintf_flt -Wl,-u,vfscanf -lscanf_flt -lm
AVRDUDEFLAGS=-c avr109 -p m328p -b 115200 -P /dev/cu.PL2303-00002014
LINKOBJECTS=../libnerdkits/delay.o ../libnerdkits/uart.o

all: button_push-upload

button_push.hex:	button_push.c
	make -C ../libnerdkits
	avr-gcc ${GCCFLAGS} ${LINKFLAGS} -o button_push.o button_push.c ${LINKOBJECTS}
	avr-objcopy -j .text -O ihex button_push.o button_push.hex
	
button_push.ass:	button_push.hex
	avr-objdump -S -d button_push.o > button_push.ass
	
button_push-upload:	button_push.hex
	avrdude ${AVRDUDEFLAGS} -e
	sleep 0.1
	avrdude ${AVRDUDEFLAGS} -D -U flash:w:button_push.hex:a
